### ISSUE TITLE
AttributeError: module 'higlass' has no attribute 'view'

### ISSUE THREAD

**Issue by LiuJie1117** [higlass/higlass-python#122]
### Question Description
Hi everyone, I am a green hand for python and jupyter Notebook. I succeeded in installing `higlass-python` (version==0.4.8) and then start to test it. 
The demo code below from HiGlass website works well, I get the HiC heatmap.
```
from higlass.client import View, Track
from higlass.tilesets import cooler\
import higlass
import os

ts0 = cooler('./tmp/sample.mcool')
tr0 = Track(track_type='heatmap', tileset=ts0,
            position='center',
            height=500)

tr1 = Track(track_type='top-axis', position='top')
tr2 = Track(track_type='left-axis', position='left')

view1 = View([tr0, tr1, tr2])

display, server, viewconf = higlass.display([view1])

display
```

However when I tested another piece of demo code, I got ERROR: `AttributeError: module 'higlass' has no attribute 'view'`
```
import higlass as hg

view1 = hg.view(hg.track("top-axis"), width=6)
view2 = hg.view(hg.track("top-axis"), width=6)

view1 | view2
```
Does it has association with version of HiGlass-python? I notice that it's recommended to install v1 with `pip install --pre higlass-python`. I don't know about the differences between version 0.4.8 and v1. 

All the demo codes in https://docs-python.higlass.io/  are compatible with version 0.4.8 and v1? Or they only work with v1? 

Thanks for any advice!

### Environment
- MacOS Monterey 12.6,  Apple M1 
- Conda: miniforge3
- Dependencies:
   - python == 3.10.6
   - jupyter notebook == 6.5.4 
   - higlass-python == 0.4.8
   - ipywidgets == 7.7.2

**Comment by LiuJie1117** [comment]
After modified my code, I got new Error: `TypeError: unsupported operand type(s) for |: 'View' and 'View'`
```
import higlass 

track1 = higlass.Track("top-axis")

view1 = higlass.View([track1], width=6)
view2 = higlass.View([higlass.Track("top-axis")],  width=6)

view1 | view2
```

**Comment by nvictus** [comment]
Hi @LiuJie1117.

The pre-release for v1 has just been turned into a release. We will no longer be supporting the old API. Please make sure you test with v1.

**Comment by LiuJie1117** [comment]
@nvictus Many thanks! It works for me.
