### ISSUE TITLE
Can higlass create a heatmap for a single resolution cool file?

### ISSUE THREAD

**Issue by Yaoyx** [higlass/higlass-python#134]
So far, it raised the ValueError: The `max_zoom` attribute is missing.

**Comment by manzt** [comment]
The cooler data-loader requires a multi-res cooler, `.mcool`. You first need to generate a multi-resolution cooler. We could probably have a better warning for this.

**Comment by Yaoyx** [comment]
> The cooler data-loader requires a multi-res cooler, `.mcool`. You first need to generate a multi-resolution cooler. We could probably have a better warning for this.

Ah I see. Thank you!
