### ISSUE TITLE
Jupyter notebook is not displaying the .mcool file

### ISSUE THREAD

**Issue by narzouni** [higlass/higlass-python#149]
Hello, I am running HiGlass on a cluster and I'm trying to use higlass-python to visualize my .mcool files. After starting Jupyter notebook through an ssh tunnel, I run the following code:

    from higlass.client import View, Track
    import higlass.tilesets
    from higlass.tilesets import cooler
    import higlass

    ts1 = cooler('Lib1_Sample1A_10kb.mcool')
    tr1 = Track('heatmap', tileset=ts1)
    view1 = View([tr1])

    display, server, viewconf = higlass.display([view1], server_port=9200)
    display

It does not display the `.mcool` file. It just shows the gray background. It does not give any errors either. Initially it was giving an error `tileset not available` but then I used another server port 9200.

Does any one have an idea why it is not displaying anything?

**Comment by narzouni** [comment]
![Screenshot 2024-05-09 at 11 05 47 AM (3)](https://github.com/higlass/higlass-python/assets/74695095/f3680ec1-8766-4e75-be15-e4e6ca808074)

**Comment by manzt** [comment]
Hi there, this code snippet is using the legacy API of `higlass-python` which is no longer supported. Please upgrade to the latest version and see the updated API documentation:

```sh
pip install --upgrade --force-reinstall higlass-python
```
