### ISSUE TITLE
instalation issue

### ISSUE THREAD

**Issue by LeilyR** [higlass/higlass-python#28]
Hi, I am trying to install higlass-python via `pip` and I face this error: 
`ERROR: Complete output from command python setup.py egg_info:`
`ERROR: # pysam: cython is available - using cythonize if necessary`
...
`FAILED.  This error must be resolved in order to build HTSlib successfully.`
...
`ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oav5foy7/pysam/`
Could you please tell me how I can resolve it

**Comment by flekschas** [comment]
Thanks for reporting this! Can you provide some background information like which version of Python you're using and which OS you're running?

This seems to be an issue related to `pysam`. @pkerpedjiev @nvictus didn't we run into issue with `pysam` before?

In the meantime, @LeilyR, if you have conda installed on your machine, would you mind trying the setup described at https://github.com/higlass/scipy19#installation? This will create an isolated conda environment, which we have tested extensively. In this repository, you will also see several example notebooks, which might be helpful for getting started.

**Comment by LeilyR** [comment]
`python --version`
`Python 3.7.3`
and I work with a ubuntu machine.
I have already made a fresh `env` for it, but sure, thanks I will look at the link you have sent me.

**Comment by nvictus** [comment]
We would need to see more of the traceback to figure out why pysam didn't compile. It's usually something like missing headers for zlib (`zlib1g-dev` on ubuntu). If you don't have sudo permissions to install such dependencies, you can install pysam using (bio)conda, as @flekschas suggested.

**Comment by LeilyR** [comment]
Unfortunately, I am already out of office, send you the full traceback  tomorrow morning.

**Comment by LeilyR** [comment]
you were right about zlib, I found this somewhere between the lines of the error message:

    configure: error: zlib development files not found
    
    HTSlib uses compression routines from the zlib library <http://zlib.net>.
    Building HTSlib requires zlib development files to be installed on the build
    machine; you may need to ensure a package such as zlib1g-dev (on Debian or
    Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions or Cygwin)
    is installed.

**Comment by pkerpedjiev** [comment]
Hey, can you try this?

```
sudo apt-get install  bzip2 libbz2-dev liblzma-dev
```

and then the pip install command? There's some libraries that are needed by a dependency.

**Comment by LeilyR** [comment]
sure, thanks!

**Comment by flekschas** [comment]
I am running into the same issue on macOS with conda now. Adding `pysam` to the `environment.yml` doesn't help. It's still failing.

**Comment by flekschas** [comment]
Adding `cytoolz` to `environment.yml` seems to fix the issue.
