### ISSUE TITLE
Is there a way to directly load available viewconfig?

### ISSUE THREAD

**Issue by fanc-WU** [higlass/higlass-python#36]
Hello,

I was trying out higlass on jupyter notebook. On 4DN data portal there are already a lot of available views with JSON format viewconfigs available, such as this one: https://data.4dnucleome.org/higlass-view-configs/4c629215-8f65-48aa-bf99-b1aedd601f4b/#details
I was wondering if there is a way to just load these available configs directly and modify on top of them, so that I don't have to re-add every track manually?
I recently switched from R to python and I'm not very clear about how things work, so please forgive me if the question is too trivial.

Thank you so much.

**Comment by flekschas** [comment]
Thanks for reaching out and trying `higlass-python`. You can absolutely do this. Please take a look at our notebook at https://github.com/higlass/scipy19/blob/master/genomics.ipynb from our SciPy conference.

You can ignore the first cell, it's only used by binder. The important part is:
```python
viewconf = ViewConf.from_link('http://higlass.io/app/?config=cX4bUPtPSIqPtsQ7r6pBGg')
```

This loads a remote viewconfig. The last cell explains how you can extend this remote viewconfig with a locally hosted track.

**Comment by fanc-WU** [comment]
> Thanks for reaching out and trying `higlass-python`. You can absolutely do this. Please take a look at our notebook at https://github.com/higlass/scipy19/blob/master/genomics.ipynb from our SciPy conference.
> 
> You can ignore the first cell, it's only used by binder. The important part is:
> 
> ```python
> viewconf = ViewConf.from_link('http://higlass.io/app/?config=cX4bUPtPSIqPtsQ7r6pBGg')
> ```
> 
> This loads a remote viewconfig. The last cell explains how you can extend this remote viewconfig with a locally hosted track.

This is really useful. Thanks!

**Comment by flekschas** [comment]
I assume your reopening was accidental and close the issue. If you run into trouble please feel free to reopen :)
