### ISSUE TITLE
2D BED file tracks not being displayed

### ISSUE THREAD

**Issue by jrhawley** [higlass/higlass-python#58]
Hi, great work with Higlass so far, I'm really impressed with this work.

**Issue**
I have some Hi-C data with a BED file of nested domains, and I'm trying to display them in a notebook, similarly to [this example with TADtree's nested domains](http://higlass.io/app/?config=IPCHmdOQR4CDY2sqj5VJHQ).
I'm able to view the heatmap without any issues, but the `2d-rectangle-domains` aren't being displayed, and I can't figure out why.
It seems like it might be an issue with ingesting the `bed2ddb` file to make a `Tileset` object.

**System information**
* Python v3.7.6
* higlass-python v0.4.0
* clodius v0.14.2
* jupyter core v4.6.2
* jupyter-notebook v6.0.3

**Minimum working example**
I've used `clodius aggregate bedpe` from the command line to create a `bed2ddb` file of the TADs positions to load them in as a track, later.
```shell
clodius aggregate bedpe \
    -a hg38 \
    --chr1-col 1 \
    --chr2-col 1 \
    --from1-col 2 \
    --from2-col 2 \
    --to1-col 3 \
    --to2-col 3 \
    -o sample.tads.bed2ddb \
    sample.tads.bed
```

For 1D BED file tracks, there are the `beddb` and `bigbed` wrapper functions that return `Tileset` objects, but there isn't one for `bed2ddb`.
I tried to make a wrapper function, myself, to ingest the tileset like so:

```python
def bed2ddb(filepath, uuid=None, **kwargs):
    from clodius.tiles.format import format_dense_tile
    from clodius.tiles.utils import tiles_wrapper_2d
    from clodius.tiles.bed2ddb import get_2d_tileset_info
    return Tileset(
        uuid=uuid,
        tileset_info=lambda: get_2d_tileset_info(filepath),
        tiles=lambda tids: tiles_wrapper_2d(
            tids,
            lambda z,x,y: format_dense_tile(tile_data(z, x, y))
        )
    )
```

Using this wrapper function, it appears that my data gets ingested, but when I go to plot it, the data doesn't get displayed.

```python
>>> tad_file = "sample.tads.bed2ddb"
>>> tad_tileset = bed2ddb(tad_file)
>>> print(tad_tileset)
<higlass.tilesets.Tileset object at 0x11d9e9a90>
>>> tad_track = Track(track_type="2d-rectangle-domains", position="center", tileset=tad_tileset, filetype="bed2ddb")
>>> print(tad_track)
{
  "type": "2d-rectangle-domains",
  "tilesetUid": "WcFmH6xaQpWSxu_G1187DQ",
  "options": {},
  "uid": "CEbzzbSfStiwI2L5vl3c6w"
}
>>> display, server, viewconf = higlass.display([View(tracks=[tad_track])])
>>> display # this leaves a blank higlass display
```

**Questions**
1. Is there a proper way to make a `bed2ddb` `Tileset` object in a Jupyter notebook? If so, can you help me, please, with what that is, since I don't think I've done it correctly here?
2. Given that the TADtree example displays properly, I know it's possible for that type of data to be loaded into Higlass. I'm wondering does the Flask/Django API for it exist, but not for the Python/Jupyter API yet?

Any help you can give would be great, thanks

**Comment by pkerpedjiev** [comment]
Hey, glad you like HiGlass and thanks for reporting this issue!

This is probably a bug on our end. Are you able to share the dataset you used?

Another useful output would be your browsers development console (cmd-option-I to load it in chrome).

**Comment by jrhawley** [comment]
Sure. I was able to get the issue with a simple example BED file.
```shell
$ cat sample.tads.bed
chr1    1760000 2640000
chr1    2640000 2760000
chr1    2760000 5960000
chr1    5960000 6440000
chr1    6440000 7960000
chr1    7960000 8360000
chr1    8360000 8880000
chr1    8880000 9600000
chr1    9600000 10160000
chr1    10160000        10440000
```

I'm using Firefox 73.0.1, and my console log writes this after executing the cell:

```shell
Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one. core.es.js:5840
Error: WebGL warning: drawElements: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once) core.es.js:12615
err: SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" hglib.js:28277
```

It looks like it stems from an error trying to fetch the data from the provided URL in the `workerGetTiles` function in the compiled `hglib.js`, which I think traces back to [here](https://github.com/higlass/higlass/blob/5659ac1e72bad60a6c5489cf3460977aef97f730/app/scripts/worker.js#L369).

**Comment by pkerpedjiev** [comment]
You were really close :-) To demonstrate, let's make sure the file is formatted appropriately:

```
tads = """chr1    1760000 2640000
chr1    2640000 2760000
chr1    2760000 5960000
chr1    5960000 6440000
chr1    6440000 7960000
chr1    7960000 8360000
chr1    8360000 8880000
chr1    8880000 9600000
chr1    9600000 10160000
chr1    10160000        10440000"""

with open('/tmp/tads.bed', 'w') as f:
    f.write(tads)
    
import subprocess as sp
ret = sp.call(['clodius', 'aggregate', 'bedpe', '--chr1-col', '1', '--chr2-col', '1', 
               '--from1-col', '2', '--from2-col', '2',
               '--to1-col', '3', '--to2-col', '3', '/tmp/tads.bed'])
```

Now we can create our `bed2ddb` function:

```
from clodius.tiles.utils import tiles_wrapper_2d

def bed2ddb(filepath, uuid=None, **kwargs):
    from clodius.tiles.bed2ddb import get_2d_tileset_info, get_2D_tiles

    return Tileset(
        uuid=uuid,
        tileset_info=lambda: get_2d_tileset_info(filepath),
        tiles=lambda tids: tiles_wrapper_2d(
            tids, lambda z, x, y: get_2D_tiles(filepath, z, x, y)[(x, y)]
        ),
        **kwargs
    )
```

To test it:

```
import higlass.tilesets as ti

ts = bed2ddb('/tmp/tads.bed.multires.db')
print(ts.tileset_info())
print(ts.tiles(['x.0.0.0']))
```
Note that the `x` in `x.0.0.0` is a tileset identifier that is ignored here.

Finally, display it in higlass:

```
from higlass.client import Track, View
import higlass

(d,s,v) = higlass.display([
    View([
        Track('top-axis'),
        Track('2d-rectangle-domains', position='center', tileset=ts, height=400)
    ], initialXDomain=[0, 20e6])
])
d
```

Et voila:

![image](https://user-images.githubusercontent.com/2143629/75086512-2949bc00-54ea-11ea-9e09-94f840a7fd09.png)

Sorry, I know this may be unnecessarily complex but we've erred on the side of flexibility, thinking that we can eventually hide the complexity with wrapper functions like `bed2ddb`.

Here's a notebook with this example: https://gist.github.com/pkerpedjiev/268d7dabf5743b6226f413982e1b4e47
And a PR I just created to add this function to the library: https://github.com/higlass/higlass-python/pull/59

**Comment by jrhawley** [comment]
Fantastic, that did it. I felt like I was close but was missing something about how that `bed2ddb` wrapper was supposed to be formed.

PR #59 looks good, that should make it much easier to load these 2D files in the next update. Thanks for the help!
