### ISSUE TITLE
set up a jupyter notebook server without root

### ISSUE THREAD

**Issue by Char-Aznable** [higlass/higlass-python#60]
Hi, I manage to set up a server and connect to it in jupyter notebook remotely. The notebook itself runs fine but when I tried executing some tutorial code in the doc like:
```
from higlass.client import View, Track
import higlass.tilesets

ts1 = higlass.tilesets.bigwig(
    'http://hgdownload.cse.ucsc.edu/goldenpath/hg19/encodeDCC/'
    'wgEncodeSydhTfbs/wgEncodeSydhTfbsGm12878InputStdSig.bigWig')

tr1 = Track('horizontal-bar', tileset=ts1)
view1 = View([tr1])
display, server, viewconf = higlass.display([view1])

display
```
the server spits out error:
```
fusermount: failed to open /etc/fuse.conf: Permission denied
fusermount: mount failed: Operation not permitted
fusermount: failed to open /etc/fuse.conf: Permission denied
fusermount: mount failed: Operation not permitted
```
and the notebook display an error message:
```
Error retrieving titlesetInfo from: http://localhost:59494/api/v1
```
The fusermount error also shows up if I am trying to load a local file. 

As I understand, solving this would require root access by adding the user to fuse group. But our system admin won't allow that due to security concerns. Is there a work around or it's an absolute requirement to have root access in order to set up a higlass jupyter server?

**Comment by flekschas** [comment]
Have you tried `display([view1], fuse=False)`? I think you don't actually need fuse when you work with local data only or am I wrong @nvictus?
