### ISSUE TITLE
it stuck at "loading"

### ISSUE THREAD

**Issue by brainfo** [higlass/higlass-python#67]
I've tested for a cool file and a bed file:
![image](https://user-images.githubusercontent.com/11832080/89252572-b756d080-d64c-11ea-953b-474cbe8bd324.png)
![image](https://user-images.githubusercontent.com/11832080/89252581-bcb41b00-d64c-11ea-98c9-1a755054f35b.png)
also for the online file (copied from your example):
![image](https://user-images.githubusercontent.com/11832080/89262753-a618be80-d662-11ea-870e-9fea433a25c7.png)
it just cannot load and display the result.
Is there anything I missed?
Thanks!

**Comment by flekschas** [comment]
Did you take a look at the web dev console? In particular the network traffic? When you see `Loading...` it means that everything initialized correctly but that for some reason the network requests do not resolve. Sometimes I noticed that higlass.io _slowed down_ for a few seconds, meaning the requests took more time to resolve than usual but that is typically just the case for a short period of time.

Having said that I don't know if the URL in your cooler tileset definition works that way. @nvictus can you confirm that this is correct or incorrect? I know this URL works in cooler but does it work in higlass-python too?

**Comment by nvictus** [comment]
>  @nvictus can you confirm that this is correct or incorrect?

It is incorrect. The HiGlass cooler tileset expects an `.mcool` path, not a specific resolution.

**Comment by nvictus** [comment]
The bed file also needs to be aggregated with clodius to work with HiGlass: http://docs.higlass.io/data_preparation.html#bed-files

**Comment by wbszhu** [comment]
Hi, nvictus
I have the same problem as you. Did you solve it?
Looking forward to your reply.

**Comment by flekschas** [comment]
As Nezar said:
1. You need to create a cooler tileset from the `.mcool` file and not a single resolution
2. You need to first aggregate bedfile before you can create a tileset out of them.

Please feel free to reopen if it still doesn't work after you've tried these two steps.
