### ISSUE TITLE
README Markdown not rendered on pypi

### ISSUE THREAD

**Issue by mccalluc** [higlass/higlass-python#7]
Markdown is not being rendered at https://pypi.org/project/higlass-python/0.1.3/, even though `long_description_content_type='text/markdown'` is in place.

Looking at [SO](https://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work) and some other sites, it's probably something out of date on the system where you are building the package before pushing.

**Comment by nvictus** [comment]
Seems to be rendering correctly now with the new travis deployment.
