### ISSUE TITLE
Unsorted .cool file

### ISSUE THREAD

**Issue by ysora** [higlass/higlass-python#70]
The chromosomes in my cool file is sorted by chr1, chr10, chr11, ... 
So when I use build-in chromosome and gene information,  chr10 is recognized as chr2.
Is there easy way to sort chromosome in the cool file or the way to upload my own chromosome and gene information?
Thanks.

**Comment by nvictus** [comment]
See this issue: https://github.com/mirnylab/cooler/issues/199

**Comment by ysora** [comment]
Thanks a lot
