### ISSUE TITLE
Unable to run NumPy example from docs

### ISSUE THREAD

**Issue by srcoulombe** [higlass/higlass-python#73]
Hi, I've been trying to run the NumPy+clodius example in the [docs](https://docs-python.higlass.io/getting_started.html#numpy-matrix) (see [jupyter notebook](https://github.com/higlass/higlass-python/blob/master/notebooks/Examples.ipynb)), but the display hangs and can't seem to progress past the "Loading..." phase. The Jupyter cell does indicate that the process has run to completion though...

Might be relate to https://github.com/higlass/higlass-python/issues/67

Could someone try to replicate this issue by running the notebook example?

**Comment by srcoulombe** [comment]
@flekschas Sorry to ping you directly, I just wanted to follow up on this issue.

**Comment by manzt** [comment]
Hi, we have updated the documentation with a new API with this feature. I'm going to close this for now, but please let me know if you run into additional issues.
