### ISSUE TITLE
change or add view/track without relauching a server with higlass.display

### ISSUE THREAD

**Issue by ruochiz** [higlass/higlass-python#74]
Hi, 

I was wondering if it's possible to change or add tracks with python code without recalling the display function? 

I'm using HiGlass-python through a jupyter notebook and want to integrate it into an app. It seems that I need to use ssh to forward the server_port of the display() from localhost to server to make the higlass display working. (Is it possible to avoid that somehow?)
 
However, I also have the need to dynamically add/change the tracks of the HiGlass display. If every time I did that I need to initiate a new HiGlass server with a new port, I would need to forward a couple of ports before running the app, which could be a problem.

Thanks in advance for your help.

**Comment by ruochiz** [comment]
Just to clairfy, I don't need to dynamically generate tracks and add them. The problem can be solved if I can add multiple tracks at once, but choose to only show one of them. (And then use python to switch which track is shown and hide the rest...)

**Comment by manzt** [comment]
Hello! We are in the process of making a new release of HiGlass Python with a completely new API that allows for this behavior. Please see the updated documentation if you have any questions!
