### ISSUE TITLE
Tutorial data unavailable

### ISSUE THREAD

**Issue by tyronechen** [higlass/higlass-python#79]
Hi all, thanks for making this package, i am very interested to use it.

[I tried to replicate the steps in the tutorial](https://docs.higlass.io/tutorial.html#prerequisites) but unfortunately cannot access the raw test data.

```
wget 'https://data.4dnucleome.org/files-processed/4DNFI2A4OBS9/@@download/4DNFI2A4OBS9.mcool' -O './sample.mcool'
--2021-06-11 13:20:09--  https://data.4dnucleome.org/files-processed/4DNFI2A4OBS9/@@download/4DNFI2A4OBS9.mcool
Resolving data.4dnucleome.org (data.4dnucleome.org)... 54.224.196.122, 3.225.21.20
Connecting to data.4dnucleome.org (data.4dnucleome.org)|54.224.196.122|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-06-11 13:20:10 ERROR 403: Forbidden.
```

Unrelated to the above, the [link to the python documentation](https://docs.python.higlass.io/) appears to be outdated on the [github page.](https://github.com/higlass/higlass-python#documentation)

**Comment by JSegueni** [comment]
It's probably because now you have to sign in to access the 4D nucleome data. 
Perhaps, it would be best to change the example dataset.
